version: '3'

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - code-share-network
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_share
      MYSQL_USER: code_share_user
      MYSQL_PASSWORD: code_share_pw
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    networks:
      - code-share-network

networks:
  code-share-network:
    name: code-share-network
    driver: bridge
