version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_share
      MYSQL_USER: cs_user
      MYSQL_PASSWORD: cs_pw
    ports:
      - '3306:3306'
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
