DROP TABLE file;

CREATE TABLE file (
    idx CHAR(36) PRIMARY KEY,
    room_idx CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    code TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    FOREIGN KEY (room_idx) REFERENCES room(idx)
);
